version: "2.1"
services:
  app:
    container_name: "nodejs"
    build: .
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    links: 
        - db
    ports:
      - "3000:3000"
    networks:
      - default 
    command: [sh, -c, "yarn prisma migrate dev && npm start"]
  db:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
networks:
  default: